### ISSUE TITLE
[Data] Filter & process issues by user, project or milestone

### ISSUE THREAD

**Issue by axwhyzee** [axwhyzee/timeline#2]
- [ ] FIlter by user
- [x] FIlter by project
- [ ] Filter by milestone
